import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import NextTopLoader from "nextjs-toploader";
import { Web3Provider } from "@/Provider/Web3provider";

export const metadata: Metadata = {
  title: "OddsHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
      <title>OddsHub | Turn Insights into Income</title>
        <meta
          name='OddsHub'
          content='On-chain prediction market on the EtherLink ecosystem.'
        />
        <link rel="icon" href="/assets/logos/oddshublogo.png" />
      </head>
      <body>
      <NextTopLoader showSpinner={false} color='#2043cf' />
      <Web3Provider>
      <main
          style={{
          flex: "1",
          width: "100%",
          height: "100%",
          overflowY: "scroll",
          }}
          >
          {children}
        </main>
      </Web3Provider>
        <Toaster />
      </body>
    </html>
  );
}
